### ISSUE TITLE
区分train_set和dev_set的长度是不是写反了

### ISSUE THREAD

**Issue by EricLee8** [zhengyima/ncov_sentiment#1]
data_process.py里的
train_end = int(len(train_list) * 1)
dev_end = int(len(train_list) * 0.9)
应该是
train_end = int(len(train_list) * 0.9)
dev_end = int(len(train_list) * 1)？

**Comment by zhengyima** [comment]
嗯，后来提交的是全数据训练的所以直接写*1了，按需要改一下就好的，谢谢反馈！
