### ISSUE TITLE
读取表格时出错，不知为何，一直不能正确返回7个值，试了很多中方法，想知道您的设置

### ISSUE THREAD

**Issue by MillionaireChen** [zhengyima/ncov_sentiment#2]
![微信截图_20200308003837](https://user-images.githubusercontent.com/35960345/76147246-3b744e80-60d5-11ea-91d7-a5e4e6ecfed7.png)
![微信截图_20200308003855](https://user-images.githubusercontent.com/35960345/76147250-3f07d580-60d5-11ea-859d-ba381897ee71.png)

**Comment by zhengyima** [comment]
print一下不是七个值的地方看一下是什么问题。

有可能是编码的问题，原始数据是gbk格式的，我有事先转成utf-8。

**Comment by MillionaireChen** [comment]
好的，我试试

**Comment by MillionaireChen** [comment]
![image](https://user-images.githubusercontent.com/35960345/76147637-5fd22a00-60d9-11ea-90c0-5a45dc4795f5.png)
这么改返回了6个属性

**Comment by MillionaireChen** [comment]
刚刚眼花看错了

**Comment by MillionaireChen** [comment]
将文件全部删除，然后用npp打开改成utf-8, 最后在open，那些函数里面加上encoding=‘utf-8’，就行了
