### ISSUE TITLE
提示错误

### ISSUE THREAD

**Issue by FourHan** [zhengyima/ncov_sentiment#5]
我使用了一个gpu 2070s 但是最后提示错误
tensorflow.python.framework.errors_impl.ResourceExhaustedError: 2 root error(s) found.
![image](https://user-images.githubusercontent.com/32974444/76513502-5e19b500-6491-11ea-9456-8f8e4aa9e0ca.png)
查了下，说是因为我资源耗尽了
emmmm，想问下楼主，你用的gpu情况，你的这个代码，我跑不起来了，【捂脸，尴尬】

此外，那个gen_res.py文件是做什么的啊

非常感谢楼主分享

**Comment by zhengyima** [comment]
TITAN V，12G左右的显存，用服务器跑的。
