### ISSUE TITLE
内存溢出

### ISSUE THREAD

**Issue by FourHan** [zhengyima/ncov_sentiment#6]
你好，我遇到了内存溢出问题，然后修改了batch_size就可以了，但是，要运行很久，想问下，你运行这个代码要运行多久才结束的哈，是不是运行完毕后，才可以产生test_result.tsv文件哈？

谢谢

**Comment by zhengyima** [comment]
我是在服务器GPU上跑的，不是用的PC，配置比较高所以十分钟左右就可以跑完。可以视自己的设备情况调整batch_size。

是的，运行完毕后才可以查看test_results.tsv。
